name: Action Workflow
on:
  workflow_call:
    inputs:
      title: 
        description: "Title"
        type: string
        default: "Enter title"
        required: false
         
jobs:
  console-log:
    runs-on: ubuntu-latest
    steps:
      - name: Print Title
        run: echo '${{ inputs.title }}'