name: Action Workflow
on:
  workflow_call:
    inputs:
      title: 
        description: "Title"
        type: string
        default: "Enter title"
        required: false
    outputs:
      date: 
        value: ${{ jobs.generate-output.outputs.date }}
         
jobs:
  console-log:
    runs-on: ubuntu-latest
    steps:
      - name: Print Title
        run: echo '${{ inputs.title }}'
  generate-output:
    runs-on: ubuntu-latest
    outputs:
      date: $ {{ steps.date-setup.outputs.date }}
    steps:
      - run: echo "date=$(date)" ?>> $GITHUB_OUTPUT
        id: date-setup