name: Artifact demo
on: push

jobs:

  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Math expresion
        run: expr 2 + 2 > math-result.txt
      - name: Upload result file
        uses: actions/upload-artifact@v4
        with:
          name: math-result-step1
          path: math-result.txt

  intrmediate-job:
    runs-on: ubuntu-latest
    needs: first-job
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: math-result-step1
      - name: Math expresion
        run: |
          value=`cat math-result.txt`
          expr $value \* 2 > math-result.txt
      - name: Upload result file
        uses: actions/upload-artifact@v4
        with:
          name: math-result-step2
          path: math-result.txt

  second-job:
    runs-on: ubuntu-latest
    needs: intrmediate-job
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: math-result-step2
      - name: Print file
        run: |
          value=`cat math-result.txt`
          echo $value
