name: Flow statements demo
on: [push]

jobs:

  job:
    runs-on: ubuntu-latest
    steps:
      - name: First step
        run: exit 1
      - name: Run on cancelled
        if: ${{ cancelled() }}
        run: echo "This job was cancelled."

      - name: Run on any case
        if: ${{ always() }}
        run: echo "Run on any case"
        
      - name: Run on success
        if: ${{ success() }}
        run: echo "Run on success case"

      - name: Run on failures
        if: ${{ failure() }}
        run: echo "Run on failure case"
    second-job:
      runs-on: ubuntu-latest
      needs: job 
      if: ${{ failure() }}
      steps:
        - run: echo "This job runs only if the first job fails."
