name: Node JS Workflow Demo
on: [push]

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache node_modules
        id: cache-step
        uses: actions/cache@v3
        with: 
          path: ~/.npm
          key: "cache-file"
      - name: Display cached files
        run: echo '${{ steps.cache-step.outputs }}'
      - name: Install node_modules dependencies
        run: nam install 
        