name: Node JS Workflow Demo
on: [workflow_dispatch]

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache node_modules
        id: cache-step
        uses: actions/cache@v3
        with: 
          path: ~/.npm
          key: "cache-file"
      - name: Display cached files
        run: echo '${{ toJson(steps.cache-step.outputs) }}'
      - name: Install node_modules dependencies
        run: npm install 
