name: Action wf testing
on: 
  workflow_dispatch:
    inputs:
      title: 
        description: "Title"
        type: sring
        default: "Enter title"
        requared: false
jobs:
  call-workflow:
    uses: ./.github/workflows/action.yaml
    with: ${{ inputs.title }}