name: Action wf testing
on: 
  workflow_dispatch:
    inputs:
      title: 
        description: "Title"
        type: string
        default: "Enter title"
        requared: false
jobs:
  call-workflow:
    uses: ./.github/workflows/action.yaml
    with: 
      title: ${{ inputs.title }}
  call-external-workflow:
    uses: sollpar/w-flows/.github/workflows/workflow.yml@main
    secrets:
      PASSWORD: $ {{ secrets.PASSWORD }}